### ISSUE TITLE
xDhcpServerOption: Router variable not working.

### ISSUE THREAD

**Issue by Ginolard** [dsccommunity/xDhcpServer#26]
No matter what you specify (single string, string array) you get the error

The variable cannot be validated because the value System.String[] is not a valid value for the Router variable.
- CategoryInfo          : MetadataError: (:) [], CimException
- FullyQualifiedErrorId : ValidateSetFailure
- PSComputerName        : localhost

**Comment by gordonbondon** [comment]
I was not able to reproduce the same error. But could it be that Router is not set because it is missing from parameters in Set-DhcpServerv4OptionValue [here](https://github.com/PowerShell/xDhcpServer/blob/0d4ecaf94aaf7b5b79dd301569b0f5bbad7894e3/DSCResources/MSFT_xDhcpServerOption/MSFT_xDhcpServerOption.psm1#L390-L413) ?

**Comment by johlju** [comment]
The resource `xDhcpServerOption` was deprecated when the resource `DhcpScopeOptionValue` was released.  The resource `xDhcpServerOption` will be removed in the next release.
